info:
  namespace: shit
recipes:
  crafting_table:
    toilet:
      permission: shit.toilet
      enabled: true
      pattern:
      - PXP
      - IXI
      - III
      ingredients:
        P: itemsadder:plastic_plate
        I: itemsadder:iron_plate
      result:
        item: shit:toilet
        amount: 1
items:
  toilet:
    display_name: display-name-toilet
    permission: toilet
    lore:
    - lore-1-toilet
    - lore-2-toilet
    resource:
      material: QUARTZ_STAIR
      generate: false
      model_path: block/toilet
    behaviours:
      furniture:
        small_hitbox: true
      furniture_sit:
        sit_height: 0.75
